spring:
  datasource:
    url: jdbc:h2:mem:job_repository_db
    username: sa
    password: sa
  batch:
    job:
      name: convertPostsJob
    jdbc:
      initialize-schema: always
  freemarker:
    enabled: true

app:
  sources:
    regular:
      wordpress-home: /path/to/wordpress/files/public_html
      wordpress-remote-base-url: http://wordpress-blog.com/
      database:
        url: jdbc:mysql://localhost:3306/wordpressdb_wp1
        username: root
        password: mysql
      tags:
        - 'regular'
      categories:
        - 'Basic posts'
    shop:
      wordpress-home: /path/to/another_wordpress/files/public_html
      wordpress-remote-base-url: http://anotherwordpress.com/
      target-resource-suffix: "-s"
      database:
        url: jdbc:mysql://localhost:3306/wordpressdb_wp2
        username: root
        password: mysql
      tags:
        - 'extra'
      categories:
        - 'Limited edition posts'
  target:
    hugo-site-content-items-dir: output/blog/content/posts


